SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
--DROP VIEW DataGuard.V#Access_Package;

CREATE VIEW [DataGuard].[V#Access_Package] AS
SELECT DISTINCT 
     SUBS.SUB_SYS, --SUBS.[DESC],
     --PAKG.CODE, --PAKG.NAME,
     SSIT.RWNO, --SSIT.NAME,
     --PKIN.RWNO,PKIN.INST_DESC,        
     USGW.GTWY_MAC_ADRS, GTWY.CPU_SRNO_DNRM     
FROM  
   DataGuard.Sub_System AS SUBS INNER JOIN
   DataGuard.Sub_System_Item AS SSIT ON SUBS.SUB_SYS = SSIT.SUB_SYS INNER JOIN
   DataGuard.Package AS PAKG ON SUBS.SUB_SYS = PAKG.SUB_SYS INNER JOIN
   DataGuard.Package_Instance AS PKIN ON PAKG.SUB_SYS = PKIN.PAKG_SUB_SYS AND PAKG.CODE = PKIN.PAKG_CODE INNER JOIN
   DataGuard.Package_Instance_User_Gateway AS PIUG ON PKIN.PAKG_SUB_SYS = PIUG.PKIN_PAKG_SUB_SYS AND PKIN.PAKG_CODE = PIUG.PKIN_PAKG_CODE AND PKIN.RWNO = PIUG.PKIN_RWNO INNER JOIN
   DataGuard.User_Gateway AS USGW ON PIUG.USGW_GTWY_MAC_ADRS = USGW.GTWY_MAC_ADRS AND PIUG.USGW_USER_ID = USGW.USER_ID AND PIUG.USGW_RWNO = USGW.RWNO INNER JOIN
   DataGuard.[User] AS [User] ON UPPER([User].USERDB) = UPPER(SUSER_NAME()) AND [User].ID = USGW.USER_ID INNER JOIN 
   DataGuard.Gateway AS GTWY ON USGW.GTWY_MAC_ADRS = GTWY.MAC_ADRS AND GTWY.VALD_TYPE_DNRM = '002' AND GTWY.AUTH_TYPE_DNRM = '002' INNER JOIN
   DataGuard.Package_Activity AS PKAC ON SSIT.SUB_SYS = PKAC.SSIT_SUB_SYS AND SSIT.RWNO = PKAC.SSIT_RWNO AND PAKG.SUB_SYS = PKAC.PAKG_SUB_SYS AND PAKG.CODE = PKAC.PAKG_CODE
WHERE  (PKAC.STAT = '002') AND (PKIN.STAT = '002') AND (USGW.VALD_TYPE = '002') AND (PIUG.STAT = '002')
  --AND   USGW.GTWY_MAC_ADRS = '84:8f:69:ac:aa:b9'
  --AND   USGW.USER_ID = 13941210170138
GO
